package;

/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

// @formatter:off
enum FmodSong {
    Fkip;
    LetsGo;
    LevelSelect;
}

enum FmodSFX {
    BearFall;
    BearSlip;
    BearSplash;
    BearStep;
    BearStepbounceOnly;
    BearStepCrunch;
    BearStepCrunchOnly;
    LifeSaverJingle;
    LifeSaverJump;
    LifeSaverNoise;
    MenuHover;
    MenuSelect;
    New_Event;
    PushCannot;
    PushIce;
    PushIceSlide;
    PushSnow;
    SealCrunch;
    SealCrunch2;
    SealDie;
    SealSqueal;
    TilesIceCollapse;
    TilesSnowToIce;
    TilesSnowToIce2;
    TilesSnowToIceSheen;
}

class FmodEvent {
    public static inline extern overload function event(song:FmodSong):String {
        return switch(song) {
            case Fkip: "event:/Music/Fkip";
            case LetsGo: "event:/Music/LetsGo";
            case LevelSelect: "event:/Music/LevelSelect";
        }
    }
    public static inline extern overload function event(sfx:FmodSFX):String {
        return switch(sfx) {
            case BearFall: "event:/SFX/Bear/BearFall";
            case BearSlip: "event:/SFX/Bear/BearSlip";
            case BearSplash: "event:/SFX/Bear/BearSplash";
            case BearStep: "event:/SFX/Bear/BearStep";
            case BearStepbounceOnly: "event:/SFX/Bear/BearStepbounceOnly";
            case BearStepCrunch: "event:/SFX/Bear/BearStepCrunch";
            case BearStepCrunchOnly: "event:/SFX/Bear/BearStepCrunchOnly";
            case LifeSaverJingle: "event:/SFX/LifeSaver/LifeSaverJingle";
            case LifeSaverJump: "event:/SFX/LifeSaver/LifeSaverJump";
            case LifeSaverNoise: "event:/SFX/LifeSaver/LifeSaverNoise";
            case MenuHover: "event:/SFX/Menu/MenuHover";
            case MenuSelect: "event:/SFX/Menu/MenuSelect";
            case New_Event: "event:/SFX/Push/New_Event";
            case PushCannot: "event:/SFX/Push/PushCannot";
            case PushIce: "event:/SFX/Push/PushIce";
            case PushIceSlide: "event:/SFX/Push/PushIceSlide";
            case PushSnow: "event:/SFX/Push/PushSnow";
            case SealCrunch: "event:/SFX/Seal/SealCrunch";
            case SealCrunch2: "event:/SFX/Seal/SealCrunch2";
            case SealDie: "event:/SFX/Seal/SealDie";
            case SealSqueal: "event:/SFX/Seal/SealSqueal";
            case TilesIceCollapse: "event:/SFX/Tiles/TilesIceCollapse";
            case TilesSnowToIce: "event:/SFX/Tiles/TilesSnowToIce";
            case TilesSnowToIce2: "event:/SFX/Tiles/TilesSnowToIce2";
            case TilesSnowToIceSheen: "event:/SFX/Tiles/TilesSnowToIceSheen";
        }
    }
}
