package;

/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

// @formatter:off
enum FmodSong {
    Fkip;
    LetsGo;
}

enum FmodSFX {
    BearFall;
    BearSplash;
    BearStep;
    BearStepbounceOnly;
    BearStepCrunch;
    BearStepCrunchOnly;
    MenuHover;
    MenuSelect;
    SealCrunch;
    SealDie;
}

class FmodEvent {
    public static inline extern overload function event(song:FmodSong):String {
        return switch(song) {
            case Fkip: "event:/Music/Fkip";
            case LetsGo: "event:/Music/LetsGo";
        }
    }
    public static inline extern overload function event(sfx:FmodSFX):String {
        return switch(sfx) {
            case BearFall: "event:/SFX/Bear/BearFall";
            case BearSplash: "event:/SFX/Bear/BearSplash";
            case BearStep: "event:/SFX/Bear/BearStep";
            case BearStepbounceOnly: "event:/SFX/Bear/BearStepbounceOnly";
            case BearStepCrunch: "event:/SFX/Bear/BearStepCrunch";
            case BearStepCrunchOnly: "event:/SFX/Bear/BearStepCrunchOnly";
            case MenuHover: "event:/SFX/Menu/MenuHover";
            case MenuSelect: "event:/SFX/Menu/MenuSelect";
            case SealCrunch: "event:/SFX/Seal/SealCrunch";
            case SealDie: "event:/SFX/Seal/SealDie";
        }
    }
}
